# Generated by Django 3.2.3 on 2024-02-27 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0006_alter_recipeingredient_recipe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeIngredient',
            new_name='IngredientInRecipe',
        ),
    ]
