# Generated by Django 3.2.3 on 2024-03-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0007_rename_recipeingredient_ingredientinrecipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='recipes', to='dishes.Tag'),
        ),
    ]
